services:
  - type: web
    name: grocalc
    env: php
    buildCommand: "./build.sh"
    startCommand: "apache2-foreground"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: sqlite
